<div class="cart-sidebar">
    <div class="cart">
        <div class="title cart-row">
            <h4>Your Cart</h4>
        </div>
        <!-- /.title -->
        <div class="entry-tickets cart-row">
            <!-- content here is generated by cart.js, function renderCartFloater() -->
        </div>
        <!-- /.entry-tickets -->
        <div class="booking-fees cart-row">
            <h4>
                Booking Fees <span class="pull-right ptBookingTotal">
                    <!-- content here is generated by cart.js, function renderCartFloater() -->
                </span>
            </h4>
        </div>
        <!-- /.booking-fees -->
        <div class="cart-total cart-row">
            <h4>
                Total <span class="pull-right ptTotalOrder">
                    <!-- content here is generated by cart.js, function renderCartFloater() -->
                </span>
            </h4>
            <?php if(!is_page('checkout')): ?>
                <div class="cta" style="display: none;">
                    <a href="/checkout/" class="btn btn-small btn-cta-color btn-bordered">Checkout</a>
                </div>
                <!-- /.cta -->
            <?php endif; ?>
        </div>
        <!-- /.cart-total -->
    </div>
    <!-- /.cart -->
</div>
<!-- /.cart-sidebar -->